# This is a basic workflow to help you get started with Actions

name: ReadmeMaker-Front-Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: create env file
        run: |
          touch .env
          cat << EOF >> .env
          ${{secrets.ENV}}

      # Runs a set of commands using the runners shell
      - name: build client files
        run: |
          yarn
          yarn build
      
      - name: zip create
        run: zip -r ReadmeMaker.zip ./*
        shell: bash
      
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 cp --region us-east-1 ./ReadmeMaker.zip s3://readme-front/ReadmeMaker.zip
      
      - name: Deploy
        run: aws deploy create-deployment
          --application-name readme-front-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name GROUP
          --s3-location bucket=readme-front,key=ReadmeMaker.zip,bundleType=zip
      
      
